export const IDENTITY_PROVISIONING_PORT = Symbol("IDENTITY_PROVISIONING_PORT");
export const SESSION_ELEVATION_PORT = Symbol("SESSION_ELEVATION_PORT");
export const AUTHORIZATION_QUERY_PORT = Symbol("AUTHORIZATION_QUERY_PORT");
