export const IDENTITY_PROVISIONING_PORT = Symbol("IDENTITY_PROVISIONING_PORT");
export const SESSION_ELEVATION_PORT = Symbol("SESSION_ELEVATION_PORT");
export const AUTHORIZATION_QUERY_PORT = Symbol("AUTHORIZATION_QUERY_PORT");
export const PLATFORM_TENANT_PROVISIONING_TRANSACTION_PORT = Symbol(
  "PLATFORM_TENANT_PROVISIONING_TRANSACTION_PORT",
);
export const MEMBERSHIP_INVITATION_TOKEN_PORT = Symbol("MEMBERSHIP_INVITATION_TOKEN_PORT");
export const MEMBERSHIP_INVITATION_ENVELOPE_PORT = Symbol("MEMBERSHIP_INVITATION_ENVELOPE_PORT");
export const TENANT_ACTIVATION_TOKEN_PORT = Symbol("TENANT_ACTIVATION_TOKEN_PORT");
export const TENANT_ACTIVATION_ENVELOPE_PORT = Symbol("TENANT_ACTIVATION_ENVELOPE_PORT");
