export const PERMISSION_KEYS = {
  platformSecurityAuditRead: "platform.security.audit.read",
  platformSecuritySessionRevoke: "platform.security.session.revoke",
  platformTenantsProvision: "platform.tenants.provision",
  platformUsersProvision: "platform.users.provision",
  tenantMembershipRead: "tenant.membership.read",
  tenantMembershipAdminInvite: "tenant.membership.admin.invite",
  tenantMembershipAdminSuspend: "tenant.membership.admin.suspend",
  tenantMembershipAdminRevoke: "tenant.membership.admin.revoke",
  tenantMembershipOwnerPromote: "tenant.membership.owner.promote",
  tenantMembershipOwnerDemote: "tenant.membership.owner.demote",
  tenantSecuritySessionRead: "tenant.security.session.read",
  tenantSecuritySessionRevoke: "tenant.security.session.revoke",
  tenantRbacPermissionRead: "tenant.rbac.permission.read",
  tenantRbacRoleRead: "tenant.rbac.role.read",
  tenantRbacRoleCreate: "tenant.rbac.role.create",
  tenantRbacRoleUpdate: "tenant.rbac.role.update",
  tenantRbacRoleArchive: "tenant.rbac.role.archive",
  tenantRbacRolePermissionGrant: "tenant.rbac.role.permission.grant",
  tenantRbacRolePermissionRevoke: "tenant.rbac.role.permission.revoke",
  tenantRbacAssignmentRead: "tenant.rbac.assignment.read",
  tenantRbacAssignmentGrant: "tenant.rbac.assignment.grant",
  tenantRbacAssignmentRevoke: "tenant.rbac.assignment.revoke",
  partnerProfileRead: "partner.profile.read",
  partnerProfileUpdate: "partner.profile.update",
  partnerApplicationRead: "partner.application.read",
  partnerApplicationSubmit: "partner.application.submit",
  partnerVerificationRead: "partner.verification.read",
  partnerVerificationUpdate: "partner.verification.update",
  partnerPayoutAccountRead: "partner.payout_account.read",
  partnerPayoutAccountUpdate: "partner.payout_account.update",
  partnerReviewFindingRead: "partner.review_finding.read",
  tenantPartnerRead: "tenant.partner.read",
  tenantPartnerVerificationRead: "tenant.partner.verification.read",
  tenantPartnerPayoutAccountRead: "tenant.partner.payout_account.read",
  tenantPartnerApplicationReview: "tenant.partner.application.review",
  tenantPartnerApplicationApprove: "tenant.partner.application.approve",
  tenantPartnerApplicationReject: "tenant.partner.application.reject",
  tenantPartnerLifecycleSuspend: "tenant.partner.lifecycle.suspend",
  tenantPartnerLifecycleReactivate: "tenant.partner.lifecycle.reactivate",
  tenantPartnerLifecycleCancel: "tenant.partner.lifecycle.cancel",
} as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[keyof typeof PERMISSION_KEYS];

export const PERMISSIONS = PERMISSION_KEYS;
export type Permission = PermissionKey;
