export const AUTHORIZATION_REPOSITORY_PORT = Symbol("AUTHORIZATION_REPOSITORY_PORT");
export const SESSION_AUTHORIZATION_REFRESH_PORT = Symbol("SESSION_AUTHORIZATION_REFRESH_PORT");
export const PROTECTED_REQUEST_AUTHORIZATION_PORT = Symbol("PROTECTED_REQUEST_AUTHORIZATION_PORT");
