export const SESSION_REPOSITORY_PORT = Symbol("SESSION_REPOSITORY_PORT");
export const SESSION_SECURITY_AUDIT_PORT = Symbol("SESSION_SECURITY_AUDIT_PORT");
export const SESSION_DIGEST_KEY = Symbol("SESSION_DIGEST_KEY");
export const LOGIN_ABUSE_METRICS_PORT = Symbol("LOGIN_ABUSE_METRICS_PORT");
export const LOGIN_ABUSE_PROTECTION_PORT = Symbol("LOGIN_ABUSE_PROTECTION_PORT");
