export const POSTGRES_POOL_TOKEN = Symbol("POSTGRES_POOL");
export const REDIS_CLIENT_TOKEN = Symbol("REDIS_CLIENT");
export const POSTGRES_READINESS_PROBE_TOKEN = Symbol("POSTGRES_READINESS_PROBE");
export const REDIS_READINESS_PROBE_TOKEN = Symbol("REDIS_READINESS_PROBE");
